import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/ThemeProviders";
import {
  Navbar,
  NavBody,
  NavItems,
  NavbarLogo,
  NavbarButton
} from "./components/ui/resizable-navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme') || 'system';
                  var systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                  var effectiveTheme = theme === 'system' ? systemTheme : theme;
                  
                  if (effectiveTheme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          {/* Navbar fixed di paling atas */}
          <div className="fixed top-0 left-0 right-0 z-50">
            <Navbar>
              <NavBody>
                <NavbarLogo />
                <NavItems
                  items={[
                    { name: "Home", link: "/" },
                    { name: "Menu", link: "/menu" },
                    { name: "Peta UMKM", link: "/peta-umkm" },
                    { name: "About", link: "/about" },
                    { name: "Blog", link: "/blog" },
                    { name: "Kontak", link: "/kontak" },
                  ]}
                />
                <NavbarButton href="/daftar" variant="primary">Daftar</NavbarButton>
              </NavBody>
            </Navbar>
          </div>
          {/* Konten halaman diberi padding top agar tidak ketutup navbar */}
          <div className="pt-14">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
