import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/ThemeProviders";
import {
  Navbar,
  NavBody,
  NavItems,
  NavbarLogo,
  NavbarButton
} from "./components/ui/resizable-navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* Navbar fixed di paling atas */}
          <div className="fixed top-0 left-0 right-0 z-50">
            <Navbar>
              <NavBody>
                <NavbarLogo />
                <NavItems
                  items={[
                    { name: "Home", link: "/" },
                    { name: "UMKM", link: "/umkm" },
                    { name: "Tentang", link: "/tentang" },
                  ]}
                />
                <NavbarButton href="/daftar" variant="primary">Daftar</NavbarButton>
              </NavBody>
            </Navbar>
          </div>
          {/* Konten halaman diberi padding top agar tidak ketutup navbar */}
          <div className="pt-14">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
